version: '3'

services:
  database:
    image: postgres
    container_name: pgsql
    # restart: always
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      # - ./create-database.sql:/docker-entrypoint-initdb.d/create-databse.sql
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=charlie
      - POSTGRES_PASSWORD=charlie123
      # - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
