version: '3.4'

services:
  mananger:
    image: emqx/edge-manager:1.1.0
    container_name: manager
    ports:
      - 9082:9082
  emqx-ee:
    image: emqx/emqx-ee:4.2.4
    container_name: emqx-ee
    ports:
      - 1883:1883 # for MQTT
      - 8083:8083
      - 8084:8084
      - 18083:18083
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: [username]
      MONGO_INITDB_ROOT_PASSWORD: [password]